### ISSUE TITLE
sound files cut short

### ISSUE THREAD

**Issue by doccrowley** [FelixdelasPozas/OGG-Extractor#2] opened 2018-05-21 13:01 UTC
extraction works, but on some to most of the sound files they cut off early and dont play the full thing or have static/screeching in them like they are corrupted

**Comment by FelixdelasPozas** [comment] 2018-05-21 21:13
Hi, what game are you using the program with? I need some details if it's a bug to sort it out. 

I've also found similar problems with other games. Those can be caused by several reasons:
- The files cutting abruptly: some files are designed to loop in-game, so in that ones the beginning and end of the song "match" or "connect". I think that "Talos Principle" had some, including some tracks that were similar (for different "moods") that also connected that way (the end of one file to the beginning of the other). That is normal and unavoidable. Games that have the full soundtrack in complete OGG files (like Hitman 2, for example) are usually rare.
- The files with noise: some games could be doing something with the data to avoid extraction. "Commandos 3: Destination Berlin" comes to mind, where the data was somewhat scrambled to avoid the soundtrack being extracted. Don't know if the reason was that the soundtrack was available for purchasing on CD. 
- There could be some false positives, that is, some parts of the data that were identified as OGG files that in fact are not. Those are shown usually as abnormaly large files. 

Please add more details and I'll try to fix it. Keep in mind that if it'a game I don't have probably I won't be able to address the issue due to not being able to look at the data. 
Thanks.

**Comment by FelixdelasPozas** [comment] 2018-06-30 06:03
I close the issue as there aren't more details about the problem.

**Closed as completed by FelixdelasPozas** 2018-06-30 06:03 UTC
